[theme]
# Thème par défaut (clair)
primaryColor = "#1E3A8A"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F6F7F9"
textColor = "#111111"
font = "sans serif"

[server]
headless = true
port = 8501

[browser]
gatherUsageStats = false
